repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  # Discarded as it requires manually re-staging auto fixed files
  # Instead use editor configuration
    # rev: v6.0.0
    # hooks:
      # - id: trailing-whitespace
        # Handle horizontal triling whitespaces
        # files: \.(php|js|ts|css|html|md|json)$
      # - id: end-of-file-fixer
        # Handle EOF whitespace issues
        # files: \.(php|js|ts|css|html|md|json)$

  - repo: local
    hooks:
      - id: general
        name: My Custom Generic Format Pre-Commit Logic
        entry: ./hooks/pre-commit-general.sh
        language: script
        files: .* ```
      
      - id: composer
        name: My Custom Composer Pre-Commit Logic
        entry: ./hooks/pre-commit-composer.sh
        language: script
        files: .* ```
      
      # PHP Linter
      - id: phpstan
        name: phpstan
        entry: phpstan analyse --memory-limit=512M
        language: system
        pass_filenames: false
        files: \.php$

      # PHP attribute consistency
      - id: php-attributes
        name: CronJob requires Agent
        entry: php hooks/check-php-attributes.php
        language: system
        files: \.php$
