{
  description = "A Nix flake for the simox project";

  inputs = {
    # Tracking the unstable channel for the latest packages
    # Main input for your everyday, up-to-date packages
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, utils }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        # The PHP extension set mirrors the framework's composer.json `ext-*`
        # contract (mysqli/pdo_mysql for the DB layer, bz2 for the
        # jakoch/phantomjs-installer composer side-effect): the flake makes
        # the extensions exist/loadable, and composer.json enforces them at
        # install (missing → hard failure).
        phpPkg = pkgs.php84.withExtensions ({ all, enabled }:
          enabled ++ [
            all.mysqli
            all.pdo_mysql
            all.bz2
          ]
        );
        # Make sure Composer uses this php, as it has the required extensions.
        phpComposer = pkgs.php84Packages.composer.override {
          php = phpPkg;
        };

        bashPkg = pkgs.bash;
        gitPkg = pkgs.git;
        mariadbPkg = pkgs.mariadb_118;
        phpLinter = pkgs.phpstan;  # Your choice for dev php linter
        pre-commit = pkgs.pre-commit; # pre-commit (Python) Framework
        # jq: runtime dependency of the `ema` CLI (pinned by the ema package),
        jqPkg = pkgs.jq;
        tmuxPkg = pkgs.tmux;

        # Common packages shared by dev and prod: the environment binaries
        # only. Framework + ema code (CLIs, dev scripts, pf-provision.sh) is
        # Composer-delivered to vendor/bin, so it is absent here; `make
        # dev-init` runs composer install to populate vendor/bin.
        commonPackages = [
          bashPkg
          phpPkg
          phpComposer
          jqPkg
          tmuxPkg
        ];
      in
      {
        # PRODUCTION ARTIFACT (Built when running 'nix build')
        # This builds the raw environment binaries, but DOES NOT spin up
        # background services.
        packages.default = pkgs.symlinkJoin {
          name = "prod-dependencies";
          paths = commonPackages;
        };

        # DEVELOPMENT ENVIRONMENT (Triggered via 'nix develop')
        devShells.default = pkgs.mkShell {
          buildInputs = commonPackages ++ [
            gitPkg
            mariadbPkg
            phpLinter
            pre-commit
          ];
          shellHook = ''
            # Private config freshness: materialize the real etc/ files from the
            # private repo (.private-source) on every shell entry, so a re-entered
            # shell never runs on stale etc/. Idempotent, and a no-op without
            # .private-source (a public checkout stays on its committed templates).
            # `make dev-init` remains the one-time bootstrap (composer install,
            # .env, hooks, hosts, ssh config).
            bin/fetch-private-data

            # PATH (vendor/bin, then bin — so the consumer `deploy` shadows the
            # framework's Composer-delivered one) is set by the framework's
            # dev-shell bootstrap sourced below: pf-shell-enter.sh owns the rule,
            # so this repo and the framework itself resolve their CLIs the same
            # way (including `ema`, which only exists in vendor/bin).
            # .env (git-ignored) is the single machine settings file,
            # generated by `make dev-init` via the framework's
            # init-local-env.sh (vendor/bin). pf-shell-enter.sh loads it (it
            # no longer starts/resumes a MariaDB daemon — the dev sandbox
            # lifecycle is owned by ema); it must be sourced (not executed)
            # from the repo root.
            [ -x vendor/bin/pf-shell-enter.sh ] && source vendor/bin/pf-shell-enter.sh simox

            # Run repo checks (non-mutating, warn-only) after entering the shell.
            # New checks are auto-discovered from checks/.
            for check in checks/*.sh; do
                [ -f "$check" ] && sh "$check"
            done

            # Customize the prompt (PS1)
            # Define ANSI color codes for readability
            CYAN='\033[0;36m'
            PURPLE='\033[0;35m'
            GREEN='\033[0;32m'
            NC='\033[0m' # No Color
            export PS1="\[$CYAN\] \u@\h:\[$GREEN\]\w\[$NC\]\$ "
          '';
        };
      }
    );
}
