{
  description = "A Nix flake for the simox project";

  inputs = {
    # Tracking the unstable channel for the latest packages
    # Main input for your everyday, up-to-date packages
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    # A specific historical commit chosen because it contains the exact version you need
    # (in this case jq)
    # Not all packages have an explicit version attribute like php84 or mariadb_118
    # nixpkgs-pinned.url = "github:nixos/nixpkgs/e6f23dc08d3624daab7094b701aa3954923c6bbb";

    utils.url = "github:numtide/flake-utils";

    # Public repo. Fetched through git (respects .gitignore), so runtime
    # artifacts such as var/mariadb/mysql.sock never enter the Nix store
    # (Nix rejects sockets with "unsupported type").
    php_daas_framework.url = "github:judijasa/php_daas_framework";
  };

  outputs = { self, nixpkgs, utils, php_daas_framework }:
    utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        # Pinned packages evaluated strictly from our historical commit input
        # pkgsPinned = import nixpkgs-pinned { inherit system; };

        #bashPkg = pkgsPinned.bash;
        bashPkg = pkgs.bash;
        gitPkg = pkgs.git;
        # gnumakePkg = pkgs.gnumake; # reproducible makefiles
        # jqPkg = pkgsPinned.jq;
        jqPkg = pkgs.jq;
        mariadbPkg = pkgs.mariadb_118;
        phpLinter = pkgs.phpstan;  # Your choice for dev php linter
        pre-commit = pkgs.pre-commit; # pre-commit (Python) Framework
        tmuxPkg = pkgs.tmux;

        # php/composer/ema come from php_daas_framework, which owns the PHP
        # runtime + required extension set (mysqli/pdo_mysql for the DB
        # layer, bz2 for its composer deps), the composer override, and the
        # pinned `ema` input — re-exported through packages.default, so
        # simox gets the `ema` CLI + init-cluster.sh via phpDaasFrameworkPkg
        # with a single reference. `runtime` is a symlinkJoin of php +
        # composer.
        phpRuntime = php_daas_framework.packages.${system}.runtime;
        phpDaasFrameworkPkg = php_daas_framework.packages.${system}.default;

        # simox↔php_daas_framework integration point: the framework's own
        # bin/phprun loads the repo-root .env from the CWD at runtime, so
        # simox ships that binary directly (phpDaasFrameworkPkg in
        # commonPackages below) — no wrapper, no baked paths, no dev/prod
        # flags. Configuration lives in .env at the repo root: `make
        # dev-init` generates it in dev; on deploy the framework `gen-env`
        # CLI regenerates it on the remote (consumer hook
        # bin/deploy/post-nix.sh — the deployed repo directory is replaced
        # on each deploy, so the gitignored .env is recreated there before
        # cron is installed). Project-agnostic: whichever `phprun` binary
        # wins the PATH race, it loads the .env of the directory it runs in.

        # Common packages shared by dev and prod. phpDaasFrameworkPkg ships
        # the phprun CLI: its bin/phprun loads the repo-root .env from the
        # CWD, so it can be dropped directly into both environments.
        commonPackages = [
          bashPkg
          # gnumakePkg
          jqPkg
          # mariadbPkg  # nix build for stateful systems is anti-pattern
          # vendor/ is in .gitignore. Generate vendor/ (via composer)
          # in prod server to avoid accidental dirty deployments.
          phpRuntime
          phpDaasFrameworkPkg
          tmuxPkg
        ];
      in
      {
        # PRODUCTION ARTIFACT (Built when running 'nix build')
        # This builds the raw binaries, but DOES NOT spin up background services.
        packages.default = pkgs.symlinkJoin {
          name = "prod-dependencies";
          paths = commonPackages;
        };

        # DEVELOPMENT ENVIRONMENT (Triggered via 'nix develop')
        devShells.default = pkgs.mkShell {
          buildInputs = commonPackages ++ [
            gitPkg
            mariadbPkg
            phpLinter
            pre-commit
          ];
          shellHook = ''
            # .env (git-ignored) is the single machine settings file,
            # generated by `make dev-init` via the framework's
            # init-local-env.sh (shipped on PATH by phpDaasFrameworkPkg).
            # shell-enter.sh loads it and resumes the local MariaDB daemon;
            # it must be sourced (not executed) from the repo root.
            # PROD_USER/DEPLOY_* live in the committed etc/deploy.conf
            # (framework `deploy` CLI contract). Nothing is exported here
            # anymore - without .env there is no data dir, so MariaDB
            # cannot be started anyway.
            source "$(command -v shell-enter.sh)"

            # Customize the prompt (PS1)
            # Define ANSI color codes for readability
            CYAN='\033[0;36m'
            PURPLE='\033[0;35m'
            GREEN='\033[0;32m'
            NC='\033[0m' # No Color
            export PS1="\[$CYAN\] \u@\h:\[$GREEN\]\w\[$NC\]\$ "

            # Inherit nix shell env in tmux (doesn't include PS1)
            # Requires `set -g default-command ...` in .tmux.conf
            PROJECT_NAME="simox"
            alias tmux="command tmux -L \$PROJECT_NAME new-session -A -s \$PROJECT_NAME"
          '';
        };
      }
    );
}
