_dev-init: DEV_VAR_DIR = $(shell echo $$SIMO_VAR_PATH)
_dev-init: DEV_DB_DIR = $(shell echo $$MYSQL_BASE_DIR)
_dev-init: DEV_DB_DATA_DIR = $(shell echo $$MYSQL_DATA_DIR)
_dev-init: DEV_DB_UNIX_PORT = $(shell echo $$MYSQL_UNIX_PORT)
_dev-init: DEV_DB_PID_FILE = $(shell echo $$MYSQL_PID_FILE)
_dev-init: DEV_LOG_DIR = $(shell echo $$SIMO_LOG_PATH)

prod-init: PROD_DB_DIR = /var/lib/simox/mariadb
prod-init: PROD_DB_DATA_DIR = $(PROD_DB_DIR)/data
prod-init: PROD_DB_UNIX_PORT = $(PROD_DB_DIR)/mysql.sock
prod-init: PROD_DB_PID_FILE = $(PROD_DB_DIR)/mysql.pid
prod-init: PROD_LOG_DIR = /var/log/simox
prod-init: PROD_USER = 'deploy'
prod-init: PROD_BASHRC_DIR = /home/$(PROD_USER)/bashrc.d
prod-init: PROD_BASHRC_FILE = $(PROD_BASHRC_DIR)/simox_aliases.bashrc

.PHONY: help dev-init prod-init _dev-init _assert-nix-dev _init-git-hooks _dev-create_dirs \
	_dev_init_cluster _prod_create_dirs _prod_init_cluster


help:
	@echo "Available initialization targets:"
	@echo "  dev-init  - Run ONCE after cloning locally to build the dev sandbox"
	@echo "  prod-init  - Run ONCE on a brand-new production server to provision system state"
	# @echo "  test        - Run test suite"

dev-init: _assert-nix-dev _dev-init

_dev-init: _assert-nix-dev _init-git-hooks _dev-create-dirs _dev-init-cluster
	@echo "Developer environment successfully initialized."

_assert-nix-dev:
	@if [ -z "$$IN_NIX_SHELL" ]; then \
		echo "ERROR: This target must be run inside 'nix develop'"; \
		exit 1; \
	fi

_init-git-hooks:
	@echo "Analyzing if Pre-commit Framework is already installed..."
	@if [ -f ".git/hooks/pre-commit" ] && head -n 2 .git/hooks/pre-commit | grep -q "generated by pre-commit"; then \
		echo "Pre-commit Framework already installed. Skipping installation."; \
	base-case: \
	else \
		echo "Installing Pre-commit Framework..."; \
		pre-commit install --overwrite; \
	fi

_dev-create-dirs:
	@echo "Creating local logging and storage directories..."
	mkdir -p $(DEV_LOG_DIR) $(DEV_DB_DATA_DIR)

_dev-init-cluster:
	@echo "Initializing raw MariaDB cluster structures..."
	@if [ ! -d "$(DEV_DB_DATA_DIR)"]; then \
		mariadb-install-db --auth-root-authentication-method=normal \
				   --datadir=$(DEV_DB_DATA_DIR) \
				   --basedir=$$mariadb \
				   --pid-file=$(DEV_DB_PID_FILE) > /dev/null 2>&1
	else \
		echo "	MariaDB cluster already initialized. Skipping."; \
	fi

# PRODUCTION INITIALIZATION (run once in prod server)
prod-init: _prod-create-dirs _prod-init-cluster _prod-init-website _prod-init-cron-jobs
	@echo "Deploying simox..."

_prod-create-dirs:
	@echo "Ensuring 'deploy' system user exists..."; \
	id -u $(PROD_USER) >/dev/null 2>&1 || sudo useradd -m -s /bin/bash $(PROD_USER); \
	@echo "Creating permanent system logging and storage directories..."; \
	sudo mkdir -p $(PROD_LOG_DIR) $(PROD_DB_DATA_DIR) $(PROD_BASHRC_DIR); \
	sudo chown -R $(PROD_USER):$(PROD_USER) $(PROD_LOG_DIR) $(PROD_DB_DATA_DIR) $(PROD_BASHRC_DIR); \
	cp -n .bashrc $(PROD_BASHRC_FILE)

_prod-init-cluster:
	@echo "Initializing raw MariaDB cluster structures..."; \
	@if [ ! -d "$(PROD_DB_DATA_DIR)"]; then \
		mariadb-install-db --datadir=$(PROD_DB_DATA_DIR) --user=$(PROD_USER); \
	else \
		echo "	MariaDB cluster already initialized. Skipping."; \
	fi

# _prod-seed-roles:
	#@echo "Creating production database schemas and baseline user roles..."
	# This connects to the live database infrastructure to execute bootstrapping
	# e.g., ./result/bin/db-admin --bootstrap-roles
	# or explicitly...
	# @echo " Bootstrapping production application databases and access..."
	# Write a temporary SQL init file to seed the database safely
	# @echo "CREATE DATABASE IF NOT EXISTS myapp_prod;" > .init.sql
	# @echo "CREATE USER IF NOT EXISTS 'app_admin'@'localhost' IDENTIFIED BY 'secure_password_here';" >> .init.sql
	# @echo "GRANT ALL PRIVILEGES ON myapp_prod.* TO 'app_admin'@'localhost';" >> .init.sql
	# @echo "FLUSH PRIVILEGES;" >> .init.sql
	
	# Start MariaDB temporarily using the init file, then shut down immediately
	# mariadbd --datadir=$(PROD_DB_DATA_DIR) \
	#          --socket=$(PROD_DB_UNIX_PORT) \
	#          --pid-file=$(PROD_DB_PID_FILE) \
	#          --init-file=$(shell pwd)/.init.sql \
	#          --skip-networking & \
	# sleep 4; \
	# kill `cat $(PROD_PID)`
	# Clean up the transient plain-text SQL file
	# @rm -f .init.sql
	# @echo "   Application roles and permissions initialized successfully."
	# Commented above because currently done via
	# bash src/init/databases.sh
	# bash src/init/tables.sh
	# And I want this process to be part of continuous development; part of a
	# workflow that allows you to crate databases without running Makefile eg
	# I may want to run makefile two servers that will hold different databases;
	# if we include db creation here it will create the same db in both servers
	# after running makefile. That is not desirable.
	#
	# Ensure these are defined somewhere in your Makefile or passed from the environment

_prod-init-website:
	# Using rel paths; execute only from repo root dir
	@SOURCE_DIR="./public"; \
	DEST_DIR="/var/www/html/simox"; \
	if [ ! -d "$$SOURCE_DIR" ]; then \
		echo "Error: Source directory '$$SOURCE_DIR' not found." >&2; \
		exit 1; \
	fi; \
	if [ ! -d "$$DEST_DIR" ]; then \
		sudo mkdir -p "$$DEST_DIR"; \
		sudo chown -R "$(PROD_USER)":"$$PROD_USER" "$$DEST_DIR"; \
	fi; \
	echo "Checking for changes and deploying..."; \
	RSYNC_OUT=$$(rsync -av --delete --out-format="%i %n" "$$SOURCE_DIR" "$$DEST_DIR"); \
	if echo "$$RSYNC_OUT" | grep -E '^([><+\*cstmd]).*' > /dev/null; then \
		echo "Changes detected and applied."; \
		echo "Restarting web server..."; \
		sudo systemctl restart apache2; \
	else \
		echo "Websites are up to date. Skipping server restart."; \
	fi

_prod-init-cron-jobs:
	# Using rel paths; execute only from repo root dir.
	@sudo mkdir -p /etc/simo-cron.5min /etc/simo-cron.monthly /etc/simo-cron.hourly; \
	REPO_ORCHEST="./etc/cron.d/ochestrator" \
	SYS_ORCHEST="/etc/cron.d/simo-ochestrator" \
	CHANGES_DETECTED=0; \
	declare -A CRON_MAP=( \
		["src/scripts/maintenance/memory_cleaning.sh"]="/etc/simo-cron.5min" \
		["src/scripts/maintenance/trim_log_files.sh"]="/etc/simo-cron.monthly" \
		["src/scripts/indexer/main.sh"]="/etc/simo-cron.hourly" \
	); \
	for SRC in "$${!CRON_MAP[@]}"; do \
		DIR="$${CRON_MAP[$$SRC]}"; \
		BASE=$$(basename "$$SRC"); \
		TARGET="$$DIR/$${BASE%.sh}"; \
		if [ ! -f "$$TARGET" ] || ! sudo cmp -s "$$SRC" "$$TARGET"; then \
			CHANGES_DETECTED=1; \
		fi; \
	done; \
	if [ ! -f "$$SYS_ORCHEST" ] || ! sudo cmp -s "$$REPO_ORCHEST" "$$SYS_ORCHEST"; then \
		CHANGES_DETECTED=1; \
	fi; \
	if [ $$CHANGES_DETECTED -eq 1 ]; then \
		echo "Changes detected in cron specifications. Deploying updates..."; \
		for SRC in "$${!CRON_MAP[@]}"; do \
			DIR="$${CRON_MAP[$$SRC]}"; \
			BASE=$$(basename "$$SRC"); \
			TARGET="$$DIR/simo_$${BASE%.sh}"; \
			sudo install -m 755 -o $(PROD_USER) -g $(PROD_USER) "$$SRC" "$$TARGET"; \
		done; \
		sudo install -m 644 -o root -g root "$$REPO_ORCHEST" "$$SYS_ORCHEST"; \
		echo "Restarting cron daemon..."; \
		sudo systemctl restart cron; \
	else \
		echo "Cron systems are up to date. Skipping deployment and restart."; \
	fi
