SHELL := $(BASH_SHELL)
_dev-init: DEV_VAR_DIR = $(shell echo $$SIMO_VAR_PATH)
_dev-init: DEV_DB_DIR = $(shell echo $$MYSQL_BASE_DIR)
_dev-init: DEV_DB_DATA_DIR = $(shell echo $$MYSQL_DATA_DIR)
_dev-init: DEV_DB_UNIX_PORT = $(shell echo $$MYSQL_UNIX_PORT)
_dev-init: DEV_DB_PID_FILE = $(shell echo $$MYSQL_PID_FILE)
_dev-init: DEV_LOG_DIR = $(shell echo $$SIMO_LOG_PATH)

prod-init: PROD_DB_DIR = /var/lib/simox/mariadb
prod-init: PROD_DB_DATA_DIR = $(PROD_DB_DIR)/data
prod-init: PROD_DB_UNIX_PORT = $(PROD_DB_DIR)/mysql.sock
prod-init: PROD_DB_PID_FILE = $(PROD_DB_DIR)/mysql.pid
prod-init: PROD_LOG_DIR = /var/log/simox
prod-init: PROD_USER = 'deploy'
prod-init: PROD_BASHRC_DIR = /home/$(PROD_USER)/bashrc.d
prod-init: PROD_BASHRC_FILE = $(PROD_BASHRC_DIR)/simox_aliases.bashrc

.PHONY: help dev-init prod-init _dev-init _assert-nix-dev _assert-dev-vars _init-git-hooks _dev-create-dirs \
    _dev-init-cluster _prod-create-dirs _prod-init-cluster _dev-init-composer _prod-init-website _prod-init-cron-jobs

help:
	@echo "Available initialization targets:"
	@echo "  dev-init   - Run ONCE after cloning locally to build the dev sandbox"
	@echo "  prod-init  - Run ONCE on a brand-new production server to provision system state"

dev-init: _assert-nix-dev _assert-dev-vars _dev-init

_dev-init: _init-git-hooks _dev-create-dirs _dev-init-cluster _dev-init-composer
	@echo "Developer environment successfully initialized."

_assert-nix-dev:
	@if [ -z "$$IN_NIX_SHELL" ]; then \
	    echo "ERROR: This target must be run inside 'nix develop'"; \
	    exit 1; \
	fi

_assert-dev-vars:
ifndef SIMO_VAR_PATH
	$(error SIMO_VAR_PATH is not set in the environment)
endif
ifndef MYSQL_DATA_DIR
	$(error MYSQL_DATA_DIR is not set in the environment)
endif

_init-git-hooks:
	@echo "Analyzing if Pre-commit Framework is already installed..."
	@if [ -f ".git/hooks/pre-commit" ] && head -n 2 .git/hooks/pre-commit | grep -q "generated by pre-commit"; then \
	    echo "Pre-commit Framework already installed. Skipping."; \
	else \
	    echo "Installing Pre-commit Framework..."; \
	    pre-commit install --overwrite; \
	fi

_dev-create-dirs:
	@echo "Creating local logging and storage directories..."
	mkdir -p $(DEV_LOG_DIR) $(DEV_DB_DATA_DIR)

_dev-init-cluster:
	@echo "Initializing raw MariaDB cluster structures..."
	@if [ ! -d "$(DEV_DB_DATA_DIR)" ]; then \
	    mariadb-install-db --auth-root-authentication-method=normal \
	                       --datadir=$(DEV_DB_DATA_DIR) \
	                       --basedir=$$mariadb \
	                       --pid-file=$(DEV_DB_PID_FILE) > /dev/null 2>&1; \
	else \
	    echo "    MariaDB cluster already initialized. Skipping."; \
	fi

_dev-init-composer:
	@echo "Installing dependencies from composer.lock..."
	@echo "Removing old composer.lock and vendor/ if they exist..."
	-rm -f composer.lock
	-rm -rf vendor
	@echo "Running composer install..."
	composer install
	@echo "Patching vendor/phpcasperjs/phpcasperjs/src/Casper.php..."
	@TARGET_FILE="vendor/phpcasperjs/phpcasperjs/src/Casper.php"; \
	sed -i 's/private $$script = \x27\x27;/protected $$script = \x27\x27;/g' "$$TARGET_FILE"

# PRODUCTION INITIALIZATION (Runs directly as root over remote SSH stream)
prod-init: _prod-create-dirs _prod-init-cluster _prod-init-website _prod-init-cron-jobs
	@echo "Deploying simox..."

_prod-create-dirs:
	@echo "Ensuring '$(PROD_USER)' system user exists..."
	@useradd -m -s /bin/bash $(PROD_USER) 2>/dev/null || echo "  User '$(PROD_USER)' already exists. Proceeding."
	@echo "Creating permanent system logging and storage directories..."
	mkdir -p $(PROD_LOG_DIR) $(PROD_DB_DATA_DIR) $(PROD_BASHRC_DIR) && \
	chown -R $(PROD_USER):$(PROD_USER) $(PROD_LOG_DIR) $(PROD_DB_DATA_DIR) $(PROD_BASHRC_DIR) && \
	cp -n .bashrc $(PROD_BASHRC_FILE) && \
	chown $(PROD_USER):$(PROD_USER) $(PROD_BASHRC_FILE)

_prod-init-cluster:
	@echo "Initializing raw MariaDB cluster structures..."
	@if [ ! -d "$(PROD_DB_DATA_DIR)" ]; then \
	    mariadb-install-db --datadir=$(PROD_DB_DATA_DIR) --user=$(PROD_USER); \
	else \
	    echo "    MariaDB cluster already initialized. Skipping."; \
	fi

_prod-init-website:
	@echo "Checking for website changes and deploying..."
	@SOURCE_DIR="./public"; \
	DEST_DIR="/var/www/html/simox"; \
	if [ ! -d "$$SOURCE_DIR" ]; then \
	    echo "Error: Source directory '$$SOURCE_DIR' not found." >&2; \
	    exit 1; \
	fi; \
	if [ ! -d "$$DEST_DIR" ]; then \
	    mkdir -p "$$DEST_DIR"; \
	fi; \
	echo "Checking for changes and deploying..."; \
	RSYNC_OUT=$$(rsync -av --delete --out-format="%i %n" "$$SOURCE_DIR" "$$DEST_DIR"); \
	chown -R $(PROD_USER):$(PROD_USER) "$$DEST_DIR"; \
	if echo "$$RSYNC_OUT" | grep -E '^([><+\*cstmd]).*' > /dev/null; then \
	    echo "Changes detected and applied. Restarting web server..."; \
	    systemctl restart apache2; \
	else \
	    echo "Websites are up to date. Skipping server restart."; \
	fi

_prod-init-cron-jobs:
	@echo "Syncing cron configurations..."
	@mkdir -p /etc/simo-cron.5min /etc/simo-cron.monthly /etc/simo-cron.hourly; \
	REPO_ORCHEST="./etc/cron.d/ochestrator"; \
	SYS_ORCHEST="/etc/cron.d/simo-ochestrator"; \
	CHANGES_DETECTED=0; \
	declare -A CRON_MAP=( ["src/scripts/maintenance/memory_cleaning.sh"]="/etc/simo-cron.5min" ["src/scripts/maintenance/trim_log_files.sh"]="/etc/simo-cron.monthly" ["src/scripts/indexer/main.sh"]="/etc/simo-cron.hourly" ); \
	for SRC in "$${!CRON_MAP[@]}"; do \
	    DIR="$${CRON_MAP[$$SRC]}"; \
	    BASE=$$(basename "$$SRC"); \
	    TARGET="$$DIR/$$BASE"; \
	    if [ ! -f "$$TARGET" ] || ! cmp -s "$$SRC" "$$TARGET"; then \
	        CHANGES_DETECTED=1; \
	    fi; \
	done; \
	if [ ! -f "$$SYS_ORCHEST" ] || ! cmp -s "$$REPO_ORCHEST" "$$SYS_ORCHEST"; then \
	    CHANGES_DETECTED=1; \
	fi; \
	if [ $$CHANGES_DETECTED -eq 1 ]; then \
	    echo "Changes detected in cron specifications. Deploying updates..."; \
	    for SRC in "$${!CRON_MAP[@]}"; do \
	        DIR="$${CRON_MAP[$$SRC]}"; \
	        BASE=$$(basename "$$SRC"); \
	        TARGET="$$DIR/simo_$${BASE%.sh}"; \
	        install -m 755 -o $(PROD_USER) -g $(PROD_USER) "$$SRC" "$$TARGET"; \
	    done; \
	    install -m 644 -o root -g root "$$REPO_ORCHEST" "$$SYS_ORCHEST"; \
	    echo "Restarting cron daemon..."; \
	    systemctl restart cron; \
	else \
	    echo "Cron systems are up to date. Skipping deployment and restart."; \
	fi
