<?php

    $cnf = parse_ini_file("src/config.sh"); // INI format similar to SH

    // Catch ext args:
    parse_str($argv[2],$ext_args);

    $opec = $ext_args['opec'];
    $attempts = (int) $ext_args['run'];
    $attempts_max = (int) $ext_args['run_max'];
    $init = $ext_args['init'];
    $last = $ext_args['last'];
    $end = $ext_args['end'];

    $message="<p>Programmed execution of <b>SIMOExpress Script</b> (main.sh)</p><p>Attempts made (get_jobs.php): ". $attempts. " (Max. ". $attempts_max. ")<br>". "Downloaded pages: ". ($last-$init+1). " (Max. ". ($end-$init+1). ")</p>";

    $stat = "<b>Error:</b> Download incomplete";
    if($last==$end){
        $stat = "<b>Success:</b> Download complete<p>". $opec;
    }
    $message .= $stat;

    // Include PHPMailer Libs...

    // linuxhint.com/how-to-send-email-from-php/

    //require '/usr/share/php/libphp-phpmailer/class.smtp.php'; // nonlocal dependency

    //***************************************
    //***************************************
    // Load PHPMailer libs as local dependency
    // using Composer.json
    // Ref: github.com/PHPMailer/PHPMailer
    //***************************************
    //Import PHPMailer classes into the global namespace
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;

    //Load Composer's autoloader
    require 'vendor/autoload.php';
    //***************************************

    ////Create an instance; passing `true` enables exceptions
    $mail = new PHPMailer(true);

    try {
        // SERVER SETTINGS
        //$mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
        $mail->IsSMTP();     //Send using SMTP
        $mail->Host = 'ssl://smtp.gmail.com';     //Set the SMTP server to send through
        $mail->SMTPAuth = true;     //Enable SMTP authentication
        $mail->Username = 'testerbd18@gmail.com';     //SMTP username
        // In Google, username coincides with mail-address
        $mail->Password = $cnf['SMTP_PASS'];    //SMTP password
        $mail->SMTPSecure = 'ssl';
        $mail->Port = 465;     //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

        // RECIPIENTS
        $mail->setFrom('admin@example.com');
        $mail->addAddress('ahelperbd@gmail.com');   // Add a recipient. 2nd arg (Opt): 'name'

        // CONTENT
        $mail->isHTML(true);
        $mail->Subject = 'Activity Monitor';
        $mail->Body = $message;
        $mail->AltBody = "This message is generated by plain text !";

        $mail->send();
        //echo 'Message has been sent';
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
?>
